name: Deploy Code
on: [push, workflow_dispatch]
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: "echo test"
        run: |
          mkdir -p ~/.ssh
          echo "${{ vars.ID_RSA }}" > ~/.ssh/id_rsa
          
          chmod 400 ~/.ssh/id_rsa
          cat ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@3.252.249.108 -o StrictHostKeyChecking=no  "touch ~/hello.txt"
          
